config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :locations
  
  devise_for :users
  
  root 'posts#index'
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user 
	has_many :locations
	has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def index	
	end

	def new
		@post = Post.find_by(params[:post_id])
		@location = Location.new
		render :new
	end

	def create
		@post = Post.find_by(params[:post_id])
		@location = @post.locations.create(location_params)
		@location.save
		redirect_to post_path(@post)
	end

	

	private
		def location_params
			params.require(:location).permit(:address, :longitude, :latitude)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
  	@posts = Post.all
  end

  def new
  	@post = current_user.posts.build
  end

  def create	
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		redirect_to post_path(@post)
  	else
  		redirect_to new_post_path
  	end
  end

  def show
  	@post = Post.find(params[:id])
  end

  private
    def post_params
    	params.require(:post).permit(:image, :description)
    end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	
	def home	
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Insty</title>
	 	  	<meta name="viewport" content="width=device-width, initial-scale=1">
	 	  	<%= csrf_meta_tags %>	
	 		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/yeti/bootstrap.min.css">
	 		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.6/flatly/bootstrap.min.css">
	 		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %> 
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container-fluid">
		    	<div class="navbar-header">
		    		<ul class="nav navbar-nav pull-left">
		    			<li><%= link_to "Insty", root_path, class: "btn-primary" %></li>
		    			<li><%= link_to "New Post", new_post_path, class: "btn-primary" %></li>
		    		</ul>
		    	    	
		    		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		    			<span class="icon-bar"></span>
		    			<span class="icon-bar"></span>
		    			<span class="icon-bar"></span>
		    		</button>	
		    	</div>
		    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		    		<ul class="nav navbar-nav pull-right">
		    			
		    				<% if current_user %>
		    					<li>
		    						<%= link_to "Log Out", destroy_user_session_path, method: :delete, confirm: "Are you sure?" %>
		    					</li>
		    				<% else %>
		    					<li>
		    					<%= link_to "Log In", new_user_session_path %>
		    					</li>
		    					<li>
		    						<%= link_to "Sign Up", new_user_registration_path %>
		    					</li>
		    				<% end %>	
		    					
		    		</ul>
		    	</div>
			</div>
		</nav> 
		<div class="container">
		<% flash.each do |a, b| %>
			<div class="alert alert-success"> <%= b %></div>
		<% end %>
			
				
	

		<%= yield %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
			
			
		</div>
	</body>
</html>

app/views/locations/index.html.erb
hello world

app/views/locations/new.html.erb
<div class="container">
	<h1>New Location</h1>
	<%= form_for [@location] do |f| %>
		<%= f.text_field :address, placeholder: "Address" %><br>
		<%= f.text_field :longitude, placeholder: "Longitude" %><br>
		<%= f.text_field :latitude, placeholder: "Latitude" %><br>
		<br>
		<%= f.submit "Submit", class:"btn btn-primary" %>
	<% end %>	
</div>

app/views/posts/index.html.erb
<% @posts.each do |x| %>
	<div class="white">
		<%= image_tag x.image.url(:medium) %>	
	</div>
	<br>
<% end %>

app/views/posts/new.html.erb
<div class="container">
	<h2>New Post</h2>
	<%= form_for @post, html: { multipart: true } do |f| %>
		<%= f.label :image %>
		<%= f.file_field :image %>
		<br>
		<%= f.label :description %>
		<%= f.text_area :description %>
		<br>
		<%= f.submit %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
	<%= image_tag(@post.image.url(:medium)) %><br>
	<%= @post.description %><br>
	<%= link_to "Add a location", new_location_path %>
</div>

app/views/statics/home.html.erb
Hello world